name: Daily Poll
on:
  schedule:
    - cron: '0 9 * * *'  # Executa diariamente às 9h

jobs:
  call_api:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to create poll
        run: |
          curl --request POST \
            --url https://whin2.p.rapidapi.com/createpoll \
            --header 'Content-Type: application/json' \
            --header 'x-rapidapi-host: whin2.p.rapidapi.com' \
            --header 'x-rapidapi-key: ${{ secrets.RAPID_API_TOKEN }}' \
            --data '{"name":"$(date +%d/%m)","optionNames":["Sim","Não"],"selectableOptionCount":1}'
